language: node_js

node_js:
  - 10
  - 9
  - 8
  - 6

before_install:
  - npm install --global npm@latest
  - npm --version

script:
  - npm run test

git:
  depth: 5

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always
