/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Color,
} from './components/sx-button/sx-button';

declare global {

  namespace StencilComponents {
    interface SxButton {
      'color': Color;
      'disabled': boolean;
      'name': string;
    }
  }

  interface HTMLSxButtonElement extends StencilComponents.SxButton, HTMLStencilElement {}

  var HTMLSxButtonElement: {
    prototype: HTMLSxButtonElement;
    new (): HTMLSxButtonElement;
  };
  interface HTMLElementTagNameMap {
    'sx-button': HTMLSxButtonElement;
  }
  interface ElementTagNameMap {
    'sx-button': HTMLSxButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sx-button': JSXElements.SxButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface SxButtonAttributes extends HTMLAttributes {
      'color'?: Color;
      'disabled'?: boolean;
      'name'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SxChip {
      'color': string;
      'text': string;
    }
  }

  interface HTMLSxChipElement extends StencilComponents.SxChip, HTMLStencilElement {}

  var HTMLSxChipElement: {
    prototype: HTMLSxChipElement;
    new (): HTMLSxChipElement;
  };
  interface HTMLElementTagNameMap {
    'sx-chip': HTMLSxChipElement;
  }
  interface ElementTagNameMap {
    'sx-chip': HTMLSxChipElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sx-chip': JSXElements.SxChipAttributes;
    }
  }
  namespace JSXElements {
    export interface SxChipAttributes extends HTMLAttributes {
      'color'?: string;
      'text'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SxDivider {

    }
  }

  interface HTMLSxDividerElement extends StencilComponents.SxDivider, HTMLStencilElement {}

  var HTMLSxDividerElement: {
    prototype: HTMLSxDividerElement;
    new (): HTMLSxDividerElement;
  };
  interface HTMLElementTagNameMap {
    'sx-divider': HTMLSxDividerElement;
  }
  interface ElementTagNameMap {
    'sx-divider': HTMLSxDividerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sx-divider': JSXElements.SxDividerAttributes;
    }
  }
  namespace JSXElements {
    export interface SxDividerAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;