/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Color,
} from './components/sx-button/sx-button';

declare global {

  namespace StencilComponents {
    interface SxButton {
      'color': Color;
      'disabled': boolean;
      'name': string;
    }
  }

  interface HTMLSxButtonElement extends StencilComponents.SxButton, HTMLStencilElement {}

  var HTMLSxButtonElement: {
    prototype: HTMLSxButtonElement;
    new (): HTMLSxButtonElement;
  };
  interface HTMLElementTagNameMap {
    'sx-button': HTMLSxButtonElement;
  }
  interface ElementTagNameMap {
    'sx-button': HTMLSxButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sx-button': JSXElements.SxButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface SxButtonAttributes extends HTMLAttributes {
      'color'?: Color;
      'disabled'?: boolean;
      'name'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;